database:
  name: incidentes
  description: >
    Base de datos para almacenar noticias sobre incidentes y accidentes en la ciudad de Tacna,
    incluyendo información del evento, sus causas, consecuencias y metadatos de extracción.

  tables:

    - name: noticias
      description: >
        Noticias extraídas de medios locales de Tacna. Contiene la información principal de cada publicación.
      columns:
        - name: id
          type: INT IDENTITY(1,1)
          constraints: [PRIMARY KEY]
          description: Identificador único de la noticia.
        - name: titulo
          type: NVARCHAR(500)
          description: Título completo de la noticia.
        - name: url
          type: NVARCHAR(500)
          description: Enlace original de la noticia.
        - name: fuente
          type: NVARCHAR(150)
          description: Medio o noticiero que publicó la noticia.
        - name: categoria
          type: NVARCHAR(100)
          description: Categoría de la noticia (por ejemplo: Actualidad, Policial, Tránsito).
        - name: fecha_publicacion
          type: DATE
          description: Fecha en la que se publicó la noticia.
        - name: fecha_extraccion
          type: DATE
          description: Fecha en la que el scraper obtuvo la noticia.
        - name: ciudad
          type: NVARCHAR(100)
          default: 'Tacna'
          description: Ciudad donde ocurrió el suceso o donde fue reportado.
        - name: sentimiento
          type: NVARCHAR(50)
          nullable: true
          description: Resultado del análisis de sentimiento del texto (positivo, negativo, neutro).

    - name: accidentes
      description: >
        Detalles estructurados de los accidentes reportados en las noticias.
      columns:
        - name: id
          type: INT IDENTITY(1,1)
          constraints: [PRIMARY KEY]
        - name: noticia_id
          type: INT
          constraints: [FOREIGN KEY REFERENCES noticias(id)]
          description: ID de la noticia relacionada.
        - name: fecha_accidente
          type: DATE
          nullable: true
          description: Fecha aproximada del accidente (si se menciona).
        - name: hora_aproximada
          type: NVARCHAR(50)
          description: Franja horaria del accidente (mañana, tarde, noche, madrugada).
        - name: dia_semana
          type: NVARCHAR(20)
          description: Día de la semana del accidente.
        - name: distrito
          type: NVARCHAR(100)
          description: Zona o distrito donde ocurrió el accidente.
        - name: tipo_via
          type: NVARCHAR(100)
          description: Tipo de vía (avenida, carretera, calle...).
        - name: tipo_accidente
          type: NVARCHAR(100)
          description: Clasificación del accidente (choque, atropello, volcadura, etc.).
        - name: causa_probable
          type: NVARCHAR(200)
          description: Causa o factor probable del accidente.
        - name: num_vehiculos_involucrados
          type: INT
          nullable: true
        - name: tipo_vehiculo
          type: NVARCHAR(100)
          description: Tipo principal de vehículo implicado (auto, moto, bus...).
        - name: condicion_clima
          type: NVARCHAR(100)
          nullable: true
        - name: num_fallecidos
          type: INT
          default: 0
        - name: num_heridos
          type: INT
          default: 0
        - name: danos_materiales
          type: NVARCHAR(50)
          description: Nivel de daños materiales (leve, moderado, grave).
        - name: intervencion_bomberos
          type: BIT
          description: Indica si intervinieron bomberos o policía (1 = sí, 0 = no).
        - name: coordenadas
          type: NVARCHAR(100)
          nullable: true
          description: Latitud y longitud estimadas para georreferenciación.
        - name: tiempo_publicacion
          type: INT
          nullable: true
          description: Diferencia (en días) entre el accidente y la publicación de la noticia.

    - name: medios
      description: >
        Tabla con información de los medios informativos (radio, prensa, televisión, digital).
      columns:
        - name: id
          type: INT IDENTITY(1,1)
          constraints: [PRIMARY KEY]
        - name: nombre
          type: NVARCHAR(150)
        - name: tipo
          type: NVARCHAR(100)
          description: Tipo de medio (radio, digital, televisión, prensa).
        - name: region
          type: NVARCHAR(100)
        - name: url_principal
          type: NVARCHAR(300)

    - name: keywords
      description: >
        Palabras clave o etiquetas extraídas de las noticias para análisis de texto o clasificación.
      columns:
        - name: id
          type: INT IDENTITY(1,1)
          constraints: [PRIMARY KEY]
        - name: noticia_id
          type: INT
          constraints: [FOREIGN KEY REFERENCES noticias(id)]
        - name: palabra_clave
          type: NVARCHAR(100)
